#!/bin/sh
/var/www/penv/bin/python /var/www/multiparser/manage.py shedule
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse
/var/www/penv/bin/python /var/www/multiparser/manage.py parse