DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
]

VIRTUAL_DISPLAY = False

SELENIUM_SAVE_SCREENSHOT_ON_OK = True
SELENIUM_SAVE_SCREENSHOT_ON_ERROR = True
SELENIUM_WAIT_TO_LOAD = 30
PARSER_LIMIT = 2
SERVER_NAME = "SOLOTONY_1"
MIN_DESCRIPTION_LENGTH = 100
MIN_INSTRUCTION_LENGTH = 20
REQUESTS_CONNECTION_TIMEOUT = 30
REQUESTS_DATA_TIMEOUT = 30
